INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23593, "Sujay Sundar", 9);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23594, "Jasmine Samadi", 12);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23595, "Allison Lee", 11);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23596, "Sujay Alluri", 11);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23597, "Bryant Chen", 11);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23598, "Pranav Nair", 11);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23599, "Pranav Denudukuri", 12);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23600, "Vishnu Nair", 9);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23601, "Anshul Vemuri", 11);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23602, "Juliann Lo", 12);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23603, "Ty Josephy", 12);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23604, "Tiffany Chen", 12);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23605, "Jason Suh", 12);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23606, "Aaron Marasia", 12);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23607, "Jake Kupferman", 11);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23608, "Janice Rateshwar", 11);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23609, "Elina Ng", 9);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23610, "Elaine Zhao", 9);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23611, "Kevin Zhu", 9);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23612, "Ada Chen", 10);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23613, "Ryan Berger", 10);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23614, "Jeff Bao", 10);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23615, "Sholly Babalola", 11);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23616, "Rishab Bhatia", 10);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23617, "Sylas Chacko", 11);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23618, "David Salmonson", 10);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23619, "Davesh Valagolam", 10);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23620, "Matt Laddy", 10);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23621, "Selena Pan", 10);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23622, "Zara Qisilbash", 10);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23623, "Elisa Ng", 10);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23624, "Enson Pan", 10);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23625, "Josh Dong", 10);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23626, "Blake Mayourian", 10);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23627, "Jeremy Rothman", 12);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23628, "Michael Pecorara", 11);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23629, "Emma Schwarzwald", 10);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23630, "Omari Motta", 10);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23631, "Gloria Cheng", 10);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23632, "Laura Zhou", 9);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23633, "Min Yoon", 9);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23634, "Josh Abbas", 9);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23635, "Alli Pearlman", 9);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23636, "Jasmine Chen", 9);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23637, "Maddy Lansberg", 10);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23638, "Andrew Chodes", 10);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23639, "Lily Glickman", 11);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23640, "Max Volynets", 12);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23641, "Sophia Chen", 12);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23642, "Judy Zhou", 12);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23643, "Andrew Lennenberg", 10);
INSERT INTO STUDENT (student_id, student_name, student_grade) VALUES   (23644, "Harrison Berger", 11);

INSERT INTO project_category_master (category_name) VALUES ("Kids Helping Pets");
INSERT INTO project_category_master (category_name) VALUES ("Stitching for care");
INSERT INTO project_category_master (category_name) VALUES ("Visiting Nursing homes");
INSERT INTO project_category_master (category_name) VALUES ("Meeting cancer patients");
INSERT INTO project_category_master (category_name) VALUES ("Socializing with elderly");
INSERT INTO project_category_master (category_name) VALUES ("Soup kitchen volunteering");
INSERT INTO project_category_master (category_name) VALUES ("Engineering toys for kids");